### ISSUE TITLE
[ DOC ] Update documentations for incidents/PerformIncidentAction

### ISSUE THREAD

**Issue by morcef** [CrowdStrike/falconpy#1000]
Hi @jshcodes,
I decided to create a new issue as I was unsure you saw my comment in https://github.com/CrowdStrike/falconpy/issues/776#issuecomment-1621609590_

It would be great if a coordinated update of available action parameters could happen in the Falcon portal, Swagger and falconpy.io :)

**Comment by jshcodes** [comment]
FalconPy documentation has been updated to reflect this new argument. This will replicate to https://falconpy.io at the top of the hour.

Thank you for reporting this! 😄
