### ISSUE TITLE
[ BUG ] Incorrect API endpoints specified in  _cspm_registration.py for GetIOAEvents and GetIOAUsers

### ISSUE THREAD

**Issue by CluelessAtCoding** [CrowdStrike/falconpy#1044]
**Describe the bug**

Using  GetIOAEvents and GetIOAUsers from CSPM_Registration always returns a page not found (404) error. 

**To Reproduce**

Perform a query using GetIOAEvents or GetIOAUsers in FalconPy. 

**Expected behavior**

Either data returned or "incorrect format" error if query incorrect. 

**Environment:**
 - OS: Windows 11 22H2
 - Python: 3.11.4
 - FalconPy: 1.3.1

**Additional context**

Examining _cspm_registration.py shows incorrect API endpoint specified:

[
    "GetIOAEvents",
    "GET",
    "**/ioa/entities/events/v1**",
    "For CSPM IOA events, gets list of IOA events.",
    "cspm_registration",

and

 [
    "GetIOAUsers",
    "GET",
    "**/ioa/entities/users/v1**",
    "For CSPM IOA users, gets list of IOA users.",
    "cspm_registration",

I believe correct API endpoint for GetIOAEvents is /detects/entities/ioa/v1

https://falcon.eu-1.crowdstrike.com/documentation/page/a879648c/cloud-security-posture-management-falcon-horizon-apis#f56cd241

Unsure as to correct API endpoint for GetIOAUsers.

**Comment by jshcodes** [comment]
Hi @CluelessAtCoding -

Thank you for pointing out this issue! 🙇 

These two operations are decommissioned and have been removed from swagger. We will update the SDK to warn that these operations are no longer available. We will also update SDK documentation to reflect these changes.

I believe the endpoint you have identified as a replacement is available as the [GetBehaviorDetections](https://www.falconpy.io/Service-Collections/CSPM-Registration.html#getbehaviordetections) operation. At this point in time, there is not a replacement for the _GetIOAUsers_ operation.

**Comment by jshcodes** [comment]
Legacy operations removed from documentation.
