### ISSUE TITLE
[ DOC ] Update Spotlight-Vulnerabilities with new vulnerability filter fields. 

### ISSUE THREAD

**Issue by crowdstrikedcs** [CrowdStrike/falconpy#1071]
**Documentation page topic**
[Documentation page topic or source code module where the issue was identified.](https://falconpy.io/Service-Collections/Spotlight-Vulnerabilities.html#available-filters)

**Describe the error or typo**
Additional filter properties are now avalaible. These should be updated

**Documentation repository:**
 - [ ] GitHub Wiki
 - [ ] falconpy.io
 - [ ] Source code - docstring

**Additional context**
To Be Added:
`apps.remediation.ids`
`cid`
`cve.is_cisa_kev`
`cve.remediation_level`
`cve.types`
`data_providers.ports`
`data_providers.provider`
`data_providers.rating`
`data_providers.scan_time`
`data_providers.scanner_id`
`host_info.asset_criticality`
`host_info.managed_by`
`host_info.internet_exposure`
`host_info.third_party_asset_ids`
`suppression_info.is_suppressed`
`suppression_info.reason`
`vulnerability_id`
`vulnerability_metadata_id`

**Comment by jshcodes** [comment]
> I am also missing
> 
> ```
> cve.cvss_attack_vector
> cve.cvss_user_interaction
> cve.cvss_integrity_impact
> host_last_seen_timestamp
> ```

For `host_last_seen_timestamp` you will need to use `last_seen_within`.  The CVSS fields do not appear to be supported as filters at this time.

**Comment by jshcodes** [comment]
- Filter table updated within wiki to reflect most recent documentation.  
- Replicated to [falconpy.io](https://falconpy.io).
