### ISSUE TITLE
[ DOC ] Default value for limit is incorrectly listed in documentation for the QueryDetects operation

### ISSUE THREAD

**Issue by dkang-firmus** [CrowdStrike/falconpy#1089]
**Documentation page topic**
- [QueryDetects operation documentation](https://falconpy.io/Service-Collections/Detects.html#querydetects)
- [QueryDetects docstring](https://github.com/CrowdStrike/falconpy/blob/main/src/falconpy/detects.py#L322)

**Describe the error or typo**
In the 'limit' field, the default value is '100', not '9999'

**Documentation repository:**
 - [x] GitHub Wiki
 - [x] falconpy.io
 - [x] Source code - [docstring](https://github.com/CrowdStrike/falconpy/blob/main/src/falconpy/detects.py#L322)

**Additional context**
Perhaps need to change the value in swagger UI as well.

**Comment by jshcodes** [comment]
Hi @dkang-firmus -

Thank you for reporting this, we will get these updated! 😄

**Comment by jshcodes** [comment]
This issue has been resolved within the [Wiki](https://github.com/CrowdStrike/falconpy/wiki/Detects#querydetects) and on [falconpy.io](https://www.falconpy.io/Service-Collections/Detects.html). The docstring correction will be included as part of the `1.3.5` release.
