### ISSUE TITLE
[Feature] Create table of contents for API docs

### ISSUE THREAD

**Issue by shawndwells** [CrowdStrike/falconpy#11]
**Describe the solution you'd like**
Table of contents for API docs such as the page at https://github.com/CrowdStrike/falconpy/wiki/detects.

**Additional context**
Table of contents to reduce scrolling around. For example:

------------------

Table of contents
=================
   * [GetAggregateDetects](https://github.com/CrowdStrike/falconpy/wiki/detects#getaggregatedetects)
   * [UpdatedDetectsByIdsV2](https://github.com/CrowdStrike/falconpy/wiki/detects#updatedetectsbyidsv2)
   * [GetDetectSummaries](https://github.com/CrowdStrike/falconpy/wiki/detects#getdetectsummaries)

------------------

Or maybe this could be a table instead:

Table of Contents
=================
| API Function | Description |
|:-|:-|
|[GetAggregateDetects](https://github.com/CrowdStrike/falconpy/wiki/detects#getaggregatedetects)|One-line summary|
|[UpdatedDetectsByIdsV2](https://github.com/CrowdStrike/falconpy/wiki/detects#updatedetectsbyidsv2)|One-line summary|
|[GetDetectSummaries](https://github.com/CrowdStrike/falconpy/wiki/detects#getdetectsummaries)|One-line summary|

**Comment by jshcodes** [comment]
This was a really good idea.  Done!

![Screen Shot 2020-12-08 at 12 46 32 AM](https://user-images.githubusercontent.com/74007258/101445123-e927be80-38ee-11eb-8c09-145d1f9ea9c6.png)
