### ISSUE TITLE
[ DOC ] Falcon Scripts not documented

### ISSUE THREAD

**Issue by Don-Swanson-Adobe** [CrowdStrike/falconpy#1102]
**Documentation page topic**
https://www.falconpy.io/Service-Collections/Real-Time-Response-Admin.html
I've found in the code where List and Get for FalconScripts has been implemented, but there is no documentation on the falconpy site yet for these commands. 

**Describe the error or typo**
Missing documentation for commands:
RTR_GetFalconScripts
RTR_ListFalconScripts

**Documentation repository:**
 - [ ] GitHub Wiki
 - [ ] falconpy.io

**Comment by jshcodes** [comment]
Hi @Don-Swanson-Adobe - 

The documentation for [`v1.3.5`](https://github.com/CrowdStrike/falconpy/releases/tag/v1.3.5) is in flight now.  ([`v1.4.0`](https://github.com/CrowdStrike/falconpy/releases/tag/v1.4.0) distracted us a little bit last month as that version had a specific release date.)

Thank you for reporting this! 😄

**Comment by jshcodes** [comment]
Hi @Don-Swanson-Adobe -

Documentation for these two operations has been completed! Let us know if there are any questions. 😄 

* [RTR_GetFalconScripts](https://www.falconpy.io/Service-Collections/Real-Time-Response-Admin.html#rtr_getfalconscripts)
* [RTR_ListFalconScripts](https://www.falconpy.io/Service-Collections/Real-Time-Response-Admin.html#rtr_listfalconscripts)
