### ISSUE TITLE
cspm_registration.get_configuration_detection_ids_v2 limit is incorrect

### ISSUE THREAD

**Issue by JamesLochheadCRWD** [CrowdStrike/falconpy#1151]
**Describe the bug**

The docs say the limit for cspm_registration.get_configuration_detection_ids_v2 is 5000, however, anything over 1000 results in an empty response. I suspect the limit for the OpenAPI endpoint is now lower and Falconpy is suppressing an Exception.

**To Reproduce**
```
response = cspm_registration.get_configuration_detection_ids_v2(limit=1001)
```

**Expected behavior**
I expected a JSON response with a body and resource elements.

**Environment (please complete the following information):**
 - OS: MacOS
 - Python: v3.12.2
 - FalconPy: 1.4.3

**Comment by jshcodes** [comment]
Documentation updated to reflect new limit value and replicated to production.
