### ISSUE TITLE
getcspmscanschedule needs lowercase cloud names

### ISSUE THREAD

**Issue by JamesLochheadCRWD** [CrowdStrike/falconpy#1152]
**Documentation page topic**
[Documentation page topic or source code module where the issue was identified.](https://www.falconpy.io/Service-Collections/CSPM-Registration.html#getcspmscanschedule)

**Describe the error or typo**
On the documentation page linked above, the names of the three cloud are mixed case (AWS, GCP, and Azure). For the endpoint to work, they MUST be lowercase. I think the docs should reflect the case required to make the endpoints work, especially since they are in code blocks.

**Comment by jshcodes** [comment]
Documentation updated to reflect lowercase values and replicated to production.
