### ISSUE TITLE
GetQueriesAlertsV2 Error in documentation 

### ISSUE THREAD

**Issue by Ni-ka-sH** [CrowdStrike/falconpy#1155]
[GetQueriesAlertsV2](https://www.falconpy.io/Service-Collections/Alerts.html?highlight=query_alerts_v2#getqueriesalertsv2)
Documentation page topic or source code module where the issue was identified.

Hi As per the Falconpy documentation, the default limit mentioned for query_alerts_v2 is 10000, but the actual default limit is 100
Can you please change this.

Attached screenshots for the same. WIthout mentiong limit, the default return is 100.

And also the max limit allowed is 1000. When i try to go beyond 1000, as per the swagger page documentation, api throws an error

![1](https://github.com/CrowdStrike/falconpy/assets/51693181/dc38e521-52e6-47fd-990a-47f9574d96d5)
![3](https://github.com/CrowdStrike/falconpy/assets/51693181/d88582ce-f047-40e0-92db-580ea2e37e8b)
![2](https://github.com/CrowdStrike/falconpy/assets/51693181/7dcfe3e2-5836-4dd4-94dd-9b8bfb5a4823)

**Comment by jshcodes** [comment]
Hi @Ni-ka-sH -

We have updated the documentation to reflect the correct default value and replicated the update to [falconpy.io](https://www.falconpy.io/Service-Collections/Alerts.html?highlight=query_alerts_v2#getqueriesalertsv2).

Thank you for reporting this issue! 🙇
