### ISSUE TITLE
[ DOC ] GetCSPMAzureAccount parameter status filter is string has no list of allowed values.

### ISSUE THREAD

**Issue by arne21a** [CrowdStrike/falconpy#1156]
**Documentation page topic**
get_azure_account - https://www.falconpy.io/Service-Collections/CSPM-Registration.html#getcspmazureaccount

**Describe the error or typo**
The fuction https://www.falconpy.io/Service-Collections/CSPM-Registration.html#getcspmazureaccount does not specify a list of status filter strings. It just states that it expects a string. Not providing a filter gives me an empty result. Guessing possible values resulted in errors.
It would be extremely beneficial to have a list of available states to filter as well as the option to not filter.

**Documentation repository:**
 - [ ] GitHub Wiki
 - [x] falconpy.io
 - [x] Source code - docstring

**Comment by jshcodes** [comment]
Hi @arne21a -

The allowed values for this field are:
- `Event_DiscoverAccountStatusProvisioned`
- `Event_DiscoverAccountStatusOperational`

We have updated the documentation on [FalconPy.io](https://www.falconpy.io/Service-Collections/CSPM-Registration.html#getcspmazureaccount) as well.

Thank you for reporting this issue!! 🙇
