### ISSUE TITLE
[ DOC ] FileVantage Documentation appears incorrect

### ISSUE THREAD

**Issue by Don-Swanson-Adobe** [CrowdStrike/falconpy#1159]
**Documentation page topic**
Documentation on the FileVantage Service Collection appears to be incomplete and missing items. 

**Describe the error or typo**
Specifically looking at the "updatepolicyhostgroups" Uber class example, there are dictionaries that are defined but not used, and when attempting to use the example provided, errors are returned by the API ( 'Invalid API operation specified.'). It appears there may be errors in some of the other examples in the FileVantage Service Collection as well. 

**Documentation repository:**
 - [ ] GitHub Wiki
 - [ ] falconpy.io
 - [ ] Source code - docstring

**Comment by jshcodes** [comment]
Relates to #1161.

**Comment by jshcodes** [comment]
This should be resolved by #1175.

Developers encountering this issue should update to FalconPy `v1.4.4` or greater.

Thank you for reporting this issue! 🙇
