### ISSUE TITLE
download_sensor.py / no error message when authentification failed

### ISSUE THREAD

**Issue by nesies** [CrowdStrike/falconpy#1162]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.
```
$ python3 download_sensor.py  -k $KEY -s $BAD_PASS -o centos

No results, check your filter and try your query again.
```

When debugging, i see that the sensors results contains:
```
{
  'status_code': 401,
  'headers': {},
  'body': {
    'errors': [
       {
           'message': 'Failed to issue token.'
       }
    ],
    'resources': []
  }
}
```
**Expected behavior**

a message saying that authentification has failed

**Environment (please complete the following information):**
 - OS: RedHat 9
 - Python: 3.9
 - FalconPy: 1.4.3

**Additional context**

**Comment by jshcodes** [comment]
Resolved by #1178.
