### ISSUE TITLE
[ DOC ] ids parameter should be composite_ids in https://falconpy.io/Service-Collections/Alerts.html#patchentitiesalertsv3

### ISSUE THREAD

**Issue by morcef** [CrowdStrike/falconpy#1166]
**Documentation page topic**
[patchentitiesalertsv3](https://falconpy.io/Service-Collections/Alerts.html#patchentitiesalertsv3)

**Describe the error or typo**
[patchentitiesalertsv3](https://falconpy.io/Service-Collections/Alerts.html#patchentitiesalertsv3) instructs to use `ids` as a parameter, when the correct parameter is `composite_ids`. 

**Documentation repository:**
 - [X] GitHub Wiki
 - [X] falconpy.io
 - [ ] Source code - docstring

**Additional context**
I also find the error message from the backend to be quite useless and misleading:
`'errors': [{'code': 400, 'message': 'invalid element in the request'}]`

**Comment by jshcodes** [comment]
Wiki content updated and replicated to [falconpy.io](https://falconpy.io).

Thank you for reporting this issue! 🙇
