### ISSUE TITLE
Sample - host_search.py - Includes comments from hostname_file in output.csv

### ISSUE THREAD

**Issue by David-M-Berry** [CrowdStrike/falconpy#1168]
**Describe the bug**
When running host_search.py and including a file with hostnames, if there are comments, the script will attempt to query for hosts with the full comment included. Comments should instead be ignored.

**To Reproduce**
1. Ensure you have a text file available with comments in it. 

```shell
test$ cat hosts.txt 
#ubuntu hosts

tester1-ubuntu
```

2. run host_search.py with the -f HOSTNAME_FILE, --hostname_file HOSTNAME_FILE option

```shell
python3 host_search.py -f hosts.txt
```
3. Observe the output.csv file as having the commented line as a hostname, and a host not found error:

```shell
test$ cat output.csv 
Hostname,CID,RFM,Last Seen,Landscape,Tag1,Tag2,Tag3,Tag4
tester1-ubuntu,<aid>,no,2023-05-28T17:54:40Z,FalconGroupingTags/devTest,
#ubuntu hosts,HOST NOT FOUND
```

**Expected behavior**
Comments in text files containing hostnames are useful for administrators, and should be ignored by the script.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python: Python 3.10.12
 - FalconPy: crowdstrike-falconpy (1.4.3)

**Comment by jshcodes** [comment]
Resolved by #1178.
