### ISSUE TITLE
[ BUG ] Missing "--base_url" argument for many scripts

### ISSUE THREAD

**Issue by cobdev** [CrowdStrike/falconpy#1181]
**Describe the bug**
It looks like most scripts lack the --base_url / -b argument capability for those who are in GovCloud. Currently, there isn't a way to consistently use falconpy to connect to "api.laggar.gcw.crowdstrike.com" rather than "api.crowdstrike.com".

**To Reproduce**
See "get_host_groups.py" for an example of a script without the "--base_url" capability:
https://github.com/CrowdStrike/falconpy/blob/main/samples/hosts/get_host_groups.py

**Expected behavior**
See "proxytool_3.4.py" for an example of a script that does have the "--base_url" capability:
https://github.com/CrowdStrike/falconpy/blob/main/samples/proxytool/proxytool_3.4.py

**Environment (please complete the following information):**
 - OS: Windows 11 Enterprise, build 23H2
 - Python: 3.12.4
 - FalconPy: 1.4.4

**Comment by jshcodes** [comment]
Hi @cobdev -

Thank you for reporting this issue! We are in the process of adding new functionality to several of our samples, and will make sure that this functionality is also included. We will leave this ticket open to track these changes.

**Comment by jshcodes** [comment]
Closing this ticket as completed.  

For samples still missing CrowdStrike region selection functionality, please post a new issue. 🙇
