### ISSUE TITLE
[ DOC ] Incorrect kwarg in doc for 'perform_policies_action' method when editing rule groups.

### ISSUE THREAD

**Issue by api-clobberer** [CrowdStrike/falconpy#1182]
**Documentation page topic**

https://www.falconpy.io/Service-Collections/Prevention-Policy.html#performpreventionpoliciesaction

**Describe the error or typo**
When using 'action_parameters' under PreventionPolicies, the docs say _group_id_ is the only available keyword that requires a value. If this doc is followed to use the endpoint to edit **IOA rule groups** with _add-rule-group_ or _remove-rule-group_, the response is a 4XX error when providing the rule group's ID to the _group_id_ keyword.

The fix is to use the keyword _rule_group_id_ in place of the _group_id_ keyword. Then, the endpoint returns a 2XX code and I can confirm that it adds the rule group to the policy specified with the _ids_ keyword.

**Documentation repository:**
 - [ ] GitHub Wiki
 - [x] falconpy.io
 - [x] Source code - docstring

**Comment by jshcodes** [comment]
Resolved and replicated to [falconpy.io](https://www.falconpy.io/Service-Collections/Prevention-Policy.html#performpreventionpoliciesaction).

Thank you for reporting this issue!
