### ISSUE TITLE
[ ENH ] Auto push to PyPi on merged pull request

### ISSUE THREAD

**Issue by shawndwells** [CrowdStrike/falconpy#12]
There are multiple GitHub Action plugins for PyPi. Let's chose one/setup something that:

- For every merged PR, generates a TEST PyPi package
- For every pushed release tag, generates an official PyPi package.

This way release engineering can be fully automated via GitOps.

@jshcodes will require API keys to PyPi. Have not used PyPi before -- is it better to create a bot account vs use personal keys? Looks like packages are static to specific users.... is that accurate? Can multiple people be added in PyPi to a package, akin to how multiple people can be added to a GitHub repo?

**Comment by jshcodes** [comment]
There is collaboration on PyPI projects. We should test multiple owners, but it looks supported. (There are two roles, maintainer and owner.  Maintainers cannot invite other collaborators, delete files, releases or the project.)

API tokens are supported, we can test this with my account to confirm.

From what I can tell, we should be able to go either way. I like the idea of there being an automation account.

**Comment by jshcodes** [comment]
PR #106 - Adds the release workflow for production package publishing. I will test it after unit testing clears using the v0.4.3 release.

**Comment by jshcodes** [comment]
> PR #106 - Adds the release workflow for production package publishing. I will test it after unit testing clears using the v0.4.3 release.

Release v0.4.3 published to the index without issue.  This workflow is now in place.  All that remains for this issue is to figure out the versioning for pushes to the test index on successful merges to main.
