### ISSUE TITLE
[ DOC ] performPreventionPoliciesAction

### ISSUE THREAD

**Issue by Don-Swanson-Adobe** [CrowdStrike/falconpy#1232]
**Documentation page topic**
Prevention Policies - performPreventionPoliciesAction

**Describe the error or typo**
The Action Parameters should be `group_id` however the documentation lists `rule_group_id`. If you use `rule_group_id` you get an Error 400: "Group action parameters must be provided"

**Documentation repository:**
 - [ ] GitHub Wiki
 - [ ] falconpy.io
 - [ ] Source code - docstring

**Comment by jshcodes** [comment]
- [x] Wiki content updated
- [x] Updates replicated to [falconpy.io](https://falconpy.io)

Thank you for reporting this issue! 😄
