### ISSUE TITLE
[ DOC ] The SECURITY.md page say all unit tests are passing, but they aren't

### ISSUE THREAD

**Issue by mraible** [CrowdStrike/falconpy#1235]
**Documentation page topic**

The [SECURITY.md](https://github.com/CrowdStrike/falconpy/blob/main/SECURITY.md) page says all CI tests are passing and displays an icon with the latest results. All say they are passing, but if you click on the "passing" badge, you'll see that the following are not passing:

- [MacOS](https://github.com/CrowdStrike/falconpy/actions/workflows/unit_testing_macos.yml)
- [Ubuntu](https://github.com/CrowdStrike/falconpy/actions/workflows/unit_testing_ubuntu.yml)
- [US2](https://github.com/CrowdStrike/falconpy/actions/workflows/unit_testing_us2.yml)
- [EU1](https://github.com/CrowdStrike/falconpy/actions/workflows/unit_testing_eu1.yml)
- [USGOV1](https://github.com/CrowdStrike/falconpy/actions/workflows/unit_testing_usgov1.yml)

The only workflow that is passing is [Windows](https://github.com/CrowdStrike/falconpy/actions/workflows/unit_testing_windows.yml). 

**Describe the error or typo**

It seems like the badges are not pulling the build status correctly, or the links aren't going to the correct place.

**Documentation repository:**
 - [x] GitHub Wiki
 - [x] falconpy.io
 - [ ] Source code - docstring

**Comment by jshcodes** [comment]
These icons only show latest status to the `main` branch for the specific test series, not all branches.
