### ISSUE TITLE
[ DOC ] Windows Certificate-Based Machine Learning Exclusions - not implemented

### ISSUE THREAD

**Issue by 59e5aaf4** [CrowdStrike/falconpy#1252]
**Describe the bug**

* "Release Notes | Windows Certificate-Based Machine Learning Exclusions" was just published

These API endpoint ( below ) are not available through falconpy, please implement :D

What you can do | Endpoint
-- | --
Create a machine learning (certificate) exclusion | POST /exclusions/entities/cert-based-exclusions/v1
Search for machine learning (certificate) exclusions | GET /exclusions/queries/cert-based-exclusions/v1
Get detailed info about one or more machine learning (certificate)   exclusions | GET /exclusions/entities/cert-based-exclusions/v1
Update settings for an existing machine learning (certificate) exclusion | PATCH /exclusions/entities/cert-based-exclusions/v1
Delete one or more machine learning (certificate) exclusions | DELETE /exclusions/entities/cert-based-exclusions/v1

**To Reproduce**

Read the documentation of falconpy, there's no mention of the cert-based-exclusions API

**Expected behavior**

1/ it's documented
2/ it's implemented 

:D

thanks !

**Comment by 59e5aaf4** [comment]
Bonus : there's "[​/exclusions​/entities​/certificates​/v1](https://assets.falcon.eu-1.crowdstrike.com/support/api/swagger.html#/certificate-based-exclusions/certificates.get.v1)" which "Retrieves certificate signing information for a file" in the swagger doc which isn't in the release message. It accepts a sample sha256
I'm wondering how all this PE cert parsing happens backstage 🤔 :D

**Comment by jshcodes** [comment]
Hi @59e5aaf4 -

This documentation is now [online](https://falconpy.io/Service-Collections/Certificate-Based-Exclusions.html).

Let us know if you have any questions or problems.  😄 🎉
