### ISSUE TITLE
[ ENH ] Please consider setting to `timeout` parameter in `requests.request` header

### ISSUE THREAD

**Issue by matcha-shake** [CrowdStrike/falconpy#163]
**Describe the information**
The following information can be found in the Reference.

> Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely:

Therefore, please consider implementing the `timeout` parameter setting within  `requests.request` header.
This is a low priority and please decide by the development members about default value of the parameter.

**References**
https://2.python-requests.org/en/master/user/quickstart/#timeouts
https://2.python-requests.org/en/master/user/advanced/#timeouts

**Comment by jshcodes** [comment]
That's a good point. I'll take care of this today.  

Thank you for the suggestion. 😁
