### ISSUE TITLE
[ Question ] Do Event Stream records include Spotlight Vulnerability Findings?

### ISSUE THREAD

**Issue by dkindlund** [CrowdStrike/falconpy#196]
After reviewing the Streaming API Event Dictionary, I couldn't find any corresponding eventTypes that map to Falcon Spotlight Vulnerability findings -- is that data also included in the Event Stream API?  Or is vulnerability information only available through polling the Falcon Spotlight APIs?

**Comment by jshcodes** [comment]
Moving this to discussions.
