### ISSUE TITLE
Cannot retrieve all the records using QueryDevicesByFilter()

### ISSUE THREAD

**Issue by tputti2** [CrowdStrike/falconpy#241]
### Discussed in https://github.com/CrowdStrike/falconpy/discussions/240

<div type='discussions-op-text'>

<sup>Originally posted by **tputti2** August  4, 2021</sup>
**Hi, I am trying to pull the device types using QueryDevicesbyFilter(), I can see that the total number of records is 11,100 but I am unable to pull more than 10,000 records** 

Code that prints the total number of records:
![image](https://user-images.githubusercontent.com/25337689/128214932-a312194f-27c4-479a-88b9-013496348c82.png)

**I am able to retrieve records from 0 to 10,000. I have to do 2 queries with each pulling 5000 records because I can only pull 5000 IDs in one call i.e. max value of 'limit' is 5000** 

![image](https://user-images.githubusercontent.com/25337689/128215522-2e2b6f46-5b77-4e67-be23-4fdfbff52cae.png)

![image](https://user-images.githubusercontent.com/25337689/128213912-33cfce56-4c1c-47c2-9497-58a8d7886017.png)

**I am unable to extract more than 10,000 records though I know the total number of records is greater than 10,000. Following is the code that gives an error. Can someone tell why this is happening? Thanks.**

![image](https://user-images.githubusercontent.com/25337689/128214022-cb4efc11-3e24-471a-8ad1-b67f13c104be.png)

</div>

**Comment by jshcodes** [comment]
Posted as a discussion, closing the issue for now.
