### ISSUE TITLE
[ BUG ] Service Class credential authentication does not respect base_url or proxy settings.

### ISSUE THREAD

**Issue by jshcodes** [CrowdStrike/falconpy#242]
**Describe the bug**
The base class of all service classes, _service_class.py does not respect values passed for the BASE_URL, PROXY or SSL_VERIFY attributes when creating an instance of the auth_object for credential authentication.

**To Reproduce**
Create an instance of any service class, and change it's base_url to US-2 or disable SSL verification with ssl_verify=False.

**Expected behavior**
The service class is instantiated with an auth_object that respects the passed attribute values.

**Environment (please complete the following information):**
 - OS: All supported
 - Python: All supported
 - FalconPy: <=0.5.5

**Comment by jshcodes** [comment]
Fix for this issue is being tested now and will be committed shortly.

**Comment by mccbryan3** [comment]
testing is good
