### ISSUE TITLE
[DOC] import statement on Prevention Policy and Sensor Update Policy service class example code

### ISSUE THREAD

**Issue by cozadk** [CrowdStrike/falconpy#306]
Documentation for the Prevention Policies and Sensor Update Policies service classes shows `from falconpy import prevention_policies as FalconPP` and `from falconpy import sensor_update_policies as FalconSUP` which threw an error for me.

It appears the valid reference is singular:
 `from falconpy import prevention_policy as FalconPP` and `from falconpy import sensor_update_policy as FalconSUP`

Not sure if this is the case with other policy classes

**Comment by jshcodes** [comment]
You are 💯 percent correct.  This is a typo, the correct reference to that specific module is singular.

The wiki documentation is out of date as compared to the functionality currently provided. This is currently being updated, and should have new content available here within the next week or so.  We will make sure this gets corrected as part of this process.  (We will also double check to confirm there are not more classes who are incorrectly documented like this.)

Thank you for pointing this out!! :smile:

**Comment by cozadk** [comment]
Sounds great.  Thanks for the quick response!

**Comment by jshcodes** [comment]
Resolved by 08.30.2021 wiki refresh. Thank you for identifying this, let us know if you find any other issues! 😀
