### ISSUE TITLE
[ BUG ] 400 error when trying to delete IOCs using the Uber class

### ISSUE THREAD

**Issue by jshcodes** [CrowdStrike/falconpy#314]
<sup>Originally posted by **Qbert777** August 23, 2021</sup>
I have a script that has been running on a cronjob without issue up until a couple of weeks ago when it started returning the following error:

**[{'code': 400, 'message': 'Either IDs or the FQL filter must be provided, not both'}]**

It uses the Uber class 'indicator.delete.v1' with param'filter':'expired:true'.  I also tried using the filter 'filter':f"expiration<'{today}'" as in the code snippet below but getting the same error.  Using falconpy ver 0.5.6.

Any ideas or suggestions are much appreciated.
Thanks.

```python
from falconpy.api_complete import APIHarness
import datetime as dt

falcon_client_id = "[REDACTED]"
falcon_client_secret = "[REDACTED]"

falcon = APIHarness(creds={
                    'client_id': falcon_client_id,
                    'client_secret': falcon_client_secret
                    }
)

today = dt.datetime.today().strftime('%Y-%m-%d')

PARAMS = {
    'filter':f"expiration<'{today}'",
    'comment':'Delete expired IOCs'
}

response = falcon.command('indicator.delete.v1', parameters=PARAMS)
print(response)
falcon.deauthenticate()
```

### Discussed in https://github.com/CrowdStrike/falconpy/discussions/313

**Environment (please complete the following information):**
 - OS: All supported
 - Python: All supported
 - FalconPy: v0.5.4 - v0.6.1

**Comment by crowdstrikedcs** [comment]
> The ids of the Indicators to delete. If both 'filter' and 'ids' are provided, then filter takes precedence and ignores ids

Odd that we are seeing this behavior with an empty ID list, worth following up on for sure.

**Comment by jshcodes** [comment]
> > The ids of the Indicators to delete. If both 'filter' and 'ids' are provided, then filter takes precedence and ignores ids
> 
> Odd that we are seeing this behavior with an empty ID list, worth following up on for sure.

Seems to only be happening with the new IOC endpoints. (The way the Uber class works at the moment, this would be occurring in lots of other places as well.)

Another interesting bit is that swagger states the filter has precedence, so it should be ignoring __ids__ regardless.
