### ISSUE TITLE
python class not found on import

### ISSUE THREAD

**Issue by sfc-gh-tlarkin** [CrowdStrike/falconpy#371]
**Describe the bug**
Using the examples from the docs I am trying to import sensor_update_policies

**To Reproduce**
In the Python shell with falconpy installed via pip
>>> from falconpy import sensor_update_policies as FalconSUP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'sensor_update_policies' from 'falconpy'

**Expected behavior**
the class is imported

**Environment (please complete the following information):**
 - OS: macOS and Amazon Linux 2
 - Python 3.8.5

**Comment by t-lark** [comment]
ah thank you, and yeah I noticed it was plural vs singular (posting from my personal gh account)

**Comment by jshcodes** [comment]
Happy to help! :smile:
