### ISSUE TITLE
[ LINK ] Handful of broken links when navigating from /Home main body

### ISSUE THREAD

**Issue by jlangdev** [CrowdStrike/falconpy#418]
**Documentation page topic**
https://falconpy.io/Home.html

**Describe the error or typo**
Several links' URLs exclude the /Usage/ URI
| referer | link | code |
|-------|------|------|
| https://falconpy.io/ | https://falconpy.io/Authenticating-to-the-API | 404 |
| https://falconpy.io/ | https://falconpy.io/Operations | 404 |
| https://falconpy.io/ | https://falconpy.io/Environment-Configuration | 404 |
| https://falconpy.io/ | https://falconpy.io/discussions | 404 |
| https://falconpy.io/ | https://falconpy.io/tree/main/samples | 404 |
| https://falconpy.io/ | https://falconpy.io/device-control-policies | 404 |
| https://falconpy.io/ | https://falconpy.io/Operations-by-Collection | 404 |
| https://falconpy.io/ | https://falconpy.io/All-Operations | 404 |

**Documentation repository:**
 - [ ] GitHub Wiki
 - [x] falconpy.io
 - [ ] Source code - docstring

**Additional context**
The URL's should look like https://falconpy.io/Usage/Authenticating-to-the-API  with the Usage URI

**Comment by jshcodes** [comment]
| referer | link | solution |
|:------|:-----|:-----|
| https://falconpy.io/ | https://falconpy.io/Authenticating-to-the-API | Redirected |
| https://falconpy.io/ | https://falconpy.io/Operations | Link updated |
| https://falconpy.io/ | https://falconpy.io/Environment-Configuration | Redirected |
| https://falconpy.io/ | https://falconpy.io/discussions | Redirected / Link updated |
| https://falconpy.io/ | https://falconpy.io/tree/main/samples | Redirected / Link updated |
| https://falconpy.io/ | https://falconpy.io/device-control-policies | Redirected |
| https://falconpy.io/ | https://falconpy.io/Operations-by-Collection | Redirected |
| https://falconpy.io/ | https://falconpy.io/All-Operations | Redirected |
