### ISSUE TITLE
[ LINK ] Missing Quick-Scan.MD

### ISSUE THREAD

**Issue by dkrull-CRWD** [CrowdStrike/falconpy#552]
**Link location**
Unable to locate Quick Scan documentation with diagrams on how it works. 

**Bad link destination**
https://github.com/CrowdStrike/falconpy/blob/main/docs/service-collections/quick-scan.md

**Correct destination**
I think the whole page is gone.

**Documentation repository:**
 - [ ] GitHub Wiki
 - [ ] falconpy.io
 - [X] Repository - MD file
 - [ ] Source code - docstring

**Additional context**
Really just looking for the documentation on how Quick Scan works with diagram

**Comment by jshcodes** [comment]
Link was not broken, but Google search results were strange.

Identified and found the Quick Scan image and documentation being hunted.

(It was this one! :smile:)

![Quick Scan](https://github.com/CrowdStrike/Cloud-AWS/raw/main/docs/img/s3-bucket-protection-process-diagram.png)

https://github.com/CrowdStrike/Cloud-AWS/tree/main/s3-bucket-protection
