### ISSUE TITLE
[ DOC ] Add evaluation_logic as an allowed facet for Spotlight Vulnerabilities queries

### ISSUE THREAD

**Issue by tsullivan06** [CrowdStrike/falconpy#608]
**Documentation page topic**
[Spotlight Combined Vulnerabilities Keyword Arguments](https://www.falconpy.io/Service-Collections/Spotlight-Vulnerabilities.html#combinedqueryvulnerabilities)

**Describe the error or typo**
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/25459335/162806127-352d27f7-6b0c-435a-8921-11579102198e.png">

The Facet option needs to updated to include 'evaluation_logic' as an option

**Documentation repository:**
 - [X] GitHub Wiki
 - [X] falconpy.io
 - [X] Source code - docstring

**Additional context**

**Comment by jshcodes** [comment]
Docstring updated, to be included within next release.

Wiki content updated, changes replicated to falconpy.io, cache updated.

![Screen Shot 2022-04-11 at 8 08 58 PM](https://user-images.githubusercontent.com/74007258/162852891-07fd53a6-f077-429d-8872-220bc86affdc.png)

Thank you for reporting this!  :smile:
