### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by sjafri2** [CrowdStrike/falconpy#68]
**Describe the bug**
During installation I am getting the below error.
"Could not find a version that satisfies the requirement crowdstrike-falconpy (from versions: )
No matching distribution found for crowdstrike-falconpy"

**To Reproduce**
pip install crowdstrike-falconpy

**Expected behavior**
Installation with out any issue.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Python: pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Additional context**
None

**Comment by jshcodes** [comment]
Due to dependencies, FalconPy only supports Python 3.6 - 3.9.

Have you tried pip3?

```shell
sudo apt install python3-pip
```
and then
```shell
pip3 install crowdstrike-falconpy
```

**Comment by jshcodes** [comment]
Next PR (#67) will contain an update for the README so that the difference between the two PIP calls is more obvious. :-)

**Comment by sjafri2** [comment]
Good morning,
The pip3 command did the magic.
thanks for the help.
