### ISSUE TITLE
[ BUG ] Crowdstrike API returning 406 for suricata latest ruleset in zip format

### ISSUE THREAD

**Issue by Derekt2** [CrowdStrike/falconpy#691]
**Describe the bug**
Following the exact documentation here: https://www.falconpy.io/Service-Collections/Intel.html#getlatestintelrulefile
Getting the ruleset with format = zip and ruleset = snort-suricata-master results in a 406 error. Changing the format to gzip returns the rules as expected.

**To Reproduce**
```
from falconpy import Intel

falcon = Intel(client_id="API_CLIENT_ID_HERE",
               client_secret="API_CLIENT_SECRET_HERE"
               )


print(falcon.get_latest_rule_file(type="snort-suricata-master", format="zip"))
```

**Expected behavior**
Return the ruleset in bytes (prior to 6/10/2022 this would happen)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python: 3.9
 - FalconPy: latest

**Comment by jshcodes** [comment]
Hi @Derekt2 -

I am able to recreate and confirm this issue.  Stand by while we look for potential root cause.  

> There have been a few commits to the samples library since 06/10/2022, but no updates to the main package.

**Comment by jshcodes** [comment]
Hi @Derekt2 - 

This was an issue on the CrowdStrike side that should now be resolved.

Could you retest for us to confirm and let us know of any issues?
