### ISSUE TITLE
[ DOC ] Active Responder Command - Bad Commands

### ISSUE THREAD

**Issue by matthewpeyton** [CrowdStrike/falconpy#722]
**Documentation page topic**
[Documentation page topic or source code module where the issue was identified.](https://falconpy.io/Service-Collections/Real-Time-Response.html#batchactiverespondercmd)

**Describe the error or typo**
Several commands which are not supported by the swagger UI are listed here - notably PUT and RUN are not accepted, as evidenced by their absence from the swagger UI page: https://assets.falcon.laggar.gcw.crowdstrike.com/support/api/swagger-eagle.html#/real-time-response/BatchActiveResponderCmd

**Documentation repository:**
 - [ ] GitHub Wiki
 - [x ] falconpy.io
 - [ ] Source code - docstring

**Additional context**
Tested not working, error code:40007, message: Command not found.

**Comment by jshcodes** [comment]
Hi @matthewpeyton -

Thank you for pointing this out! `PUT` and `RUN` are admin commands, we will get this table updated asap.

Did you encounter any issues when you moved your code over to use [BatchAdminCmd](https://www.falconpy.io/Service-Collections/Real-Time-Response-Admin.html#batchadmincmd) for these commands?

**Comment by jshcodes** [comment]
This table has been updated and replicated to [falconpy.io](https://falconpy.io).  

Thank you again for identifying this issue! 😄
