### ISSUE TITLE
[ DOC ] GetOnlineState_V1 operation is missing from Hosts documentation

### ISSUE THREAD

**Issue by tsullivan06** [CrowdStrike/falconpy#738]
**Documentation page topic**
Host APIs

**Describe the error or typo**
The 'GetOnlineState' is not listed in the table of contents 
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/25459335/181032923-1af51bee-f084-4228-9f4d-f661a4e03f9a.png">

(https://www.falconpy.io/Service-Collections/Hosts.html?highlight=online#getonlinestate_v1)

**Documentation repository:**
 - [ ] GitHub Wiki
 - [ X] falconpy.io
 - [ ] Source code - docstring

**Additional context**

**Comment by jshcodes** [comment]
Missing link added to TOC. Replicated to [falconpy.io](https://falconpy.io).
