### ISSUE TITLE
[ DOC ] perform_incident_action includes "comments" in verbose description but not as keyword arguments

### ISSUE THREAD

**Issue by seiimonn** [CrowdStrike/falconpy#776]
**Documentation page topic**
falconpy/incidents.py -> line 120

**Describe the error or typo**
In the sourcecode of `falconpy/incidents.py` the description on line 123 states that the function `perform_incident_action` can be used to add comments to an incident. In the description of the keyword arguments following there is no reference to any actions possible for comments.

**Documentation repository:**
 - Source code - docstring

**Comment by jshcodes** [comment]
Thank you for reporting this!  :smile:

**Comment by morcef** [comment]
@jshcodes , sorry for commenting on a closed issue, but I just passed by as I saw the documentation at [falconpy.io](https://falconpy.io/Service-Collections/Incidents.html#performincidentaction) still states the same as the documentarion at [Swagger](https://assets.falcon.eu-1.crowdstrike.com/support/api/swagger-eu.html#/incidents/PerformIncidentAction);

> Perform a set of actions on one or more incidents, such as adding tags or _**comments**_ or updating the incident name or description

After some digging, I found that it is the documentation at https://falcon.eu-1.crowdstrike.com/documentation/86/detections-monitoring-apis#modify-incidents that is lacking details of the available action paramters. It is in fact possible to add a comment to an incident by using the action parameter name: "add_comment".

I guess it would be a good idea to update the documentations around :) And it would also be nice to have an own keyword argument for add_comment ;)
