### ISSUE TITLE
[ DOC ] Redundant variable definition in QueryDetects operation documentation.

### ISSUE THREAD

**Issue by tsullivan06** [CrowdStrike/falconpy#790]
**Documentation page topic**
[Documentation page topic or source code module where the issue was identified.](https://www.falconpy.io/Service-Collections/Detects.html#querydetects)
QueryDetects --- Uber Class Example

**Describe the error or typo**
Uber Class Example: 
I believe that the 'PARAMS' dictionary is redundant as those variables are already called out in the API call itself.

**Documentation repository:**
 - [X] GitHub Wiki
 - [X] falconpy.io
 - [ ] Source code - docstring

**Additional context**

**Comment by jshcodes** [comment]
Legacy text removed.  Content replicated to [falconpy.io](https://www.falconpy.io/Service-Collections/Detects.html#querydetects).
