### ISSUE TITLE
[ BUG ] ServiceClass object state does not fully synchronise with an auth_object

### ISSUE THREAD

**Issue by ChristopherHammond13** [CrowdStrike/falconpy#829]
**Describe the bug**
FalconPy will, by design, store state about a token within each service class. This is effectively a shadow / mirror of a lot of the data stored within an `OAuth2` `auth_object` instance. However, when you initialise multiple `ServiceClass` derivatives (for example, both `RealTimeResponse` and `RealTimeResponseAdmin`) with the same `OAuth2` object, an update to a token by one `ServiceClass` is not reflected in another. This results in calls from the other class (i.e., the one that did not recently update the token) attempting to use an old JWT, which results in failed API requests. This is in spite of the `auth_object` reporting that the token is up to date (because it is, since the other `ServiceClass` already triggered the refresh during another API call).

**To Reproduce**
- Create an `OAuth2` `auth_object`
- Create *both* a `RealTimeResponse` and `RealTimeResponseAdmin` `ServiceClass` object
- Use the `RealTimeResponse` class to make an API call
- Wait 20 mins
- Use the `RealTimeResponse` class again to trigger a token renewal
- Wait another 10 minutes
- Attempt to use the `RealTimeResponseAdmin` command. It will likely fail, as the token appears to be up to date (it is! `RealTimeResponse` already triggered the renewal), but it will not as `self.token` (the token copy stored within the `RealTimeResponseAdmin` object) will be old and will still reflect the token when the classes were originally set up.

**Expected behavior**
The complete set of state for authentication should exist *only* within the `OAuth2` class / `auth_object`, so that when an authentication object is shared between Service Classes they are working off the same data. This would save lots of code in `_service_class.py`, reduce complexity, and ensure that JWTs can be easily shared between multiple concurrently used Service Classes (such as in [Caracara](https://github.com/CrowdStrike/caracara)).

**Environment (please complete the following information):**
 - OS: Windows
 - Python: 3.10
 - FalconPy: 1.2.3

**Additional context**
This bug was identified in an application built on Caracara, which likely brought the bug to light because of the (by design!) shared `OAuth2` object.

**Comment by jshcodes** [comment]
This issue is __confirmed__. Related to technical debt within the base Service Class object (and a couple of methods within `_util.py`), we will be addressing this issue separately in a stand alone branch ([_ver_1.3.0_](https://github.com/CrowdStrike/falconpy/tree/ver_1.3.0)).

This development will not impact the upcoming __1.2.4__ release, which is posting to the [__*dev*__](https://github.com/CrowdStrike/falconpy/tree/dev) branch now.
