### ISSUE TITLE
[ ENH ] filter for API does not require urlencode, which sometimes generates ambiguous results

### ISSUE THREAD

**Issue by aboese** [CrowdStrike/falconpy#850]
**Describe the bug**
filter for API does not require urlencode, which sometimes produces unexpected results.

**To Reproduce**
Use crowdstrike API without urlencoding filter

**Expected behavior**
There are cases where this works fine and some where it does not. When it does not work fine, that is the urlencode is needed for symbols, and the symbols parse incorrectly, remaining in the get string but remaining unparsed because of the misinterpretation. I am going to suggest that if you continue to support not urldecoding (which is fine) that Ambiguously parsed queries get a 300 return code, which may or may not be detectable through standard type checking and checking what portion of a query is either parsed but meaningless, or not parsable but meaningless. 

I realize that most of the non-encoded that work will encode automatically.

**Environment (please complete the following information):**
API only

**Additional context**
I am silly.

**Comment by jshcodes** [comment]
This is an interesting one.  The hard part (like you point out) will be detecting the parsing failure on the return.

Do you have a filter example or two that you know will generate a parsing failure?

I think changing the return code is good idea.  If we can detect the bad query parsing and return a 300 with detail, that's more helpful than the generic error message they'd receive from the API (or worse, unusual / invalid results depending on how the filter is mangled).

[Version 1.3.0](https://github.com/CrowdStrike/falconpy/tree/ver_1.3.0) is on the horizon (I'm _very_ excited about it) and is addressing several issues similar to this (it will also include a slew of new pythonic error conditions). I'm going to leave this open for now and tag it as an enhancement.  If we're able to recreate this, I think we should add it as another exception type.

**Comment by aboese** [comment]
The simple one I can think of is an and which in FQL is a plus ‘+’ but of course gets translated to a space. If you wanted an and, but instead use a space you’ll probably end up with either the first value getting mistyped as a string, which may or may not make sense. Or it might just end up as stray text on a filter. Either of those would constitute ambiguity. 

-Alex Boese

>

**Comment by aboese** [comment]
For this example, you could probably do a simple translate of spaces into pluses for the filter, and if the filter parse works better, then issue a 300. It’s a fine line, or course.

-Alex

>

**Comment by jshcodes** [comment]
> For this example, you could probably do a simple translate of spaces into pluses for the filter, and if the filter parse works better, then issue a 300. It’s a fine line, or course.

Basically a pre-flight check.  🤔

There aren't a ton of [FQL](https://www.falconpy.io/Usage/Falcon-Query-Language.html) symbols to worry about, so that solution might result in a relatively small number of pre-checks to perform. 

If we do decide to do it, we should also look at the `sort` keyword and see what happens if we mangle it's contents as well.

**Comment by aboese** [comment]
I’m silly so this might be an excessive request, or it might help other silly people.

-A

**Comment by jshcodes** [comment]
If it doesn't harm functionality or performance, and has the potential to be helpful, I'm willing to implement [silly](https://github.com/CrowdStrike/falconpy/blob/ver_1.3.0/src/falconpy/_util/_functions.py#L553). :smile:

Requests takes care of everything for us in the current iteration, the implied assumption is they know this based upon our documentation.  That being said, handling an exception if they don't _should_ be doable. (There might be other benefits here, payload validation does exist in some places already.)

I'll try and garf up a few filters using the 1.3 codebase and see what happens.  That'll give me a chance to experiment with any other impacts we might not be thinking of.
