### ISSUE TITLE
[ DOC ] "FQL syntax" is obscure, please provide simple examples like "created_timestamp.desc"

### ISSUE THREAD

**Issue by 59e5aaf4** [CrowdStrike/falconpy#897]
**Documentation page topic**
In the policy prevention doc, https://www.falconpy.io/Service-Collections/Prevention-Policy.html#querycombinedpreventionpolicies , says we can sort policies (it's a paginated endpoint, so sorting is needed), but doesn't provide examples. The source code at https://github.com/CrowdStrike/falconpy/blob/main/src/falconpy/prevention_policy.py#L432 mentions the field names and says "FQL syntax" assuming that is common knowledge or documented somewhere.

I had to look up in the psfalcon source code to figure out how to sort these by adding the `.desc` suffix.

https://github.com/CrowdStrike/psfalcon/blob/master/Public/policy-prevention.ps1#L128 

**Documentation repository:**
 - [x] GitHub Wiki
 - [x] falconpy.io
 - [x] Source code - docstring

**Additional context**

Please enhance the doc by providing some `.asc` or `.desc` examples around these code locations

Thanks !

**Comment by jshcodes** [comment]
Hi @59e5aaf4 -

Thank you for pointing this out, we will get this page updated (and spend some time on the FQL syntax page as well). 😀

**Comment by jshcodes** [comment]
Added example to Prevention Policy documentation.  More expansion of FQL documentation across Service Collections is planned.
