### ISSUE TITLE
404 on token 

### ISSUE THREAD

**Issue by NSH531** [CrowdStrike/falconpy#899]
I havent access to token beacuse the api in changes (thrown mee 404)
```
import requests
import json

client_id = 'YOUR_CLIENT_ID'
client_secret = 'YOUR_CLIENT_SECRET'
url = "https://api.crowdstrike.com/oauth2/token"

data = {
    'client_id': client_id,
    'client_secret': client_secret
}

response = requests.post(url, data=data)
if response.status_code == 200:
    token = json.loads(response.text)["access_token"]
    print(token)
else:
    print("Error:", response.status_code)

```

**Comment by NSH531** [comment]
hi, This is the crowdstrike token API please see api url: https://api.crowdstrike.com/oauth2/token

**Comment by jshcodes** [comment]
For details on how to authenticate using the `crowdstrike-falconpy` library, please see this page: https://www.falconpy.io/Usage/Authenticating-to-the-API.html
