### ISSUE TITLE
[ DOC ] Document providing a filename to the ssl_verify keyword for trusted certificates

### ISSUE THREAD

**Issue by jshcodes** [CrowdStrike/falconpy#910]
__Documentation page topic__
[Environment configuration](https://www.falconpy.io/Usage/Environment-Configuration.html).

**Documentation repository:**
 - [x] GitHub Wiki
 - [x] falconpy.io
 - [x] Source code - docstring

**Additional context**
### Discussed in https://github.com/CrowdStrike/falconpy/discussions/908

<div type='discussions-op-text'>

<sup>Originally posted by **lostpolaris** February 13, 2023</sup>
Hey ya'll, 

Was just wondering if we can pass in proxies to this library using Environment Variables and also, if we're behind a corporate proxies that does SSL/TLS inspection, how do we pass in trusted certs to the library? 

HTTPX / Requests usually allow for a path to be sent instead of a boolean as part of ssl_verify, but I don't see it in the documentation for the library. 

Thanks!</div>

**Comment by NSH531** [comment]
Hi,
How do I can to login to api with ip instead fqdn?
Thanks,
Nate

בתאריך יום ג׳, 14 בפבר׳ 2023, 0:33, מאת Joshua Hiller ‏<
***@***.***>:

**Comment by jshcodes** [comment]
Wiki content updated. Content replication will occur to falconpy.io at the top of the hour.
