### ISSUE TITLE
[ DOC ] combinedQueryVulnerabilities operation supports 5000 results

### ISSUE THREAD

**Issue by cactusjuan** [CrowdStrike/falconpy#922]
**Documentation page topic**
Documentation page topic or source code module where the issue was identified.
https://www.falconpy.io/Service-Collections/Spotlight-Vulnerabilities.html#combinedqueryvulnerabilities

**Describe the error or typo**
A clear and concise description of where the issue occurs.
The limit states 400 is the max results it can return but in the swagger documentation, it is 5000. Tested and 5000 works

**Documentation repository:**
 - [x] GitHub Wiki
 - [x] falconpy.io
 - [x] Source code - docstring

**Additional context**

**Comment by jshcodes** [comment]
Confirmed new limit is accurate, updating documentation.  (Thank you for pointing this out! 😄)
