### ISSUE TITLE
[ BUG ] Can't get custom CSPM policies

### ISSUE THREAD

**Issue by notdodo** [CrowdStrike/falconpy#929]
**Describe the bug**
using `get_policy_settings`  APIs does not return custom CSPM policies created from the web UI.

**To Reproduce**
1. creat a custom CSPM policy named `testcustom`
2. use https://github.com/CrowdStrike/falconpy/blob/main/samples/cspm_registration/get_cspm_policies.py do download the policies
3. `testcustom` policy is not returned

**Expected behavior**
The API should return also the custom policies

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python: 3.10.6
 - FalconPy: 1.2.12

**Comment by jshcodes** [comment]
Hi @notdodo -

I've confirmed this operation is functioning as expected. At this point in time, custom policies are not available via the API.

This is an excellent API enhancement suggestion, you should consider posting it as an [IDEA](https://us-1.ideas.crowdstrike.com/).
