### ISSUE TITLE
[ BUG ] Intermittent 500 errors being returned by the RTR batch_init_sessions method

### ISSUE THREAD

**Issue by halloffame0793** [CrowdStrike/falconpy#971]
**Describe the bug**
When executing  the RTR batch_init_sessions method certain batches are returning the following error while other batches are successful -  {code: 500, messasge: Internal Server Error: Please provice trace-id=**** to support}. 

**To Reproduce**
Initiate RTR batch session on a large amount of hosts utilizing mutliple batches. (issue is intermittent)

**Expected behavior**
As we have been running this logic for multiple months and have not observed this impact we would expect successful sesison batches or a more specific error message.

**Environment (please complete the following information):**
 - OS: Windows & Linux
 - Python: 3.9
 - FalconPy: 1.2.9

**Additional context**

**Comment by jshcodes** [comment]
Hi @halloffame0793 -

A couple of follow up questions:
- Do you have an idea of when this behavior started?
- About how often is it happening?  (10% of the time? 50%?)

**Comment by morcef** [comment]
Hi @jshcodes,
I must admit this seems somewhat familiar. I created support case 00957534 - INTERNAL_FAIL When Collecting Detailed Recon Notifications. It should be noted that I was using a totally different API than in this issue, but I was also receiving non-telling errors (same as reported here). I had my hypothesis about why I was getting the error, but I never got it verified by support. From my testing I was getting this error whenever the server used more than 30 seconds to process my request (you should be able to see by the dialogue and attachments in my case). I am not sure if there might be a similar timeout occurring with this API as well, so I just wanted to point out the possible similarity.
Anyways, I totally agree with @halloffame0793 that the error definitely should contain more context as to why the error occurred.

**Comment by halloffame0793** [comment]
@jshcodes apoligies for the late reply. I also have a support case open for this issue.  Please see this case for addition details. Case 01057826

**Comment by jshcodes** [comment]
> @morcef: I am not sure if there might be a similar timeout occurring with this API as well, so I just wanted to point out the possible similarity. 

Thank you for pointing this out! I'll try and prove this if I'm able.

> @halloffame0793: I also have a support case open for this issue.

I'm researching the case notes now and will work with Support to try and recreate this issue.
