### ISSUE TITLE
Invalid Parameter: Detects: UpdateDetectsByIdsV2: assigned_to_uuid

### ISSUE THREAD

**Issue by dkang-firmus** [CrowdStrike/falconpy#993]
**Documentation page topic**
Documentation page topic or source code module where the issue was identified.

**Describe the error or typo**
Description of allowed parameter is wrong.
URL: https://falconpy.io/Service-Collections/Detects.html#updatedetectsbyidsv2
Initial Value: A user ID (Ex: user@somewhere.com) to assign the detection to.
Suggested Value: A user UID (Ex: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) to assign the detection to.

**Documentation repository:**
 - [ ] GitHub Wiki
 - [/] falconpy.io
 - [ ] Source code - docstring

**Additional context**

**Comment by jshcodes** [comment]
@dkang-firmus -

This wiki page has been updated to provide a valid example for the `assigned_to_uuid` keyword and synchronized with https://falconpy.io.

__Thank you__ for pointing this out! 🙇
